Name: qmlsettings
Summary: Settings application made with QML
Version: 0.0.0
Release: 1
Group: Applications/System
License: BSD
URL: https://github.com/nemomobile/qmlsettings/
Sources:
    - "%{name}-%{version}.tar.bz2"
Description: Settings application written using QML.
PkgConfigBR:
    - QtDeclarative
Requires:
    - qt-components
    - nemo-qml-plugin-time
    - nemo-qml-plugin-accounts
    - nemo-qml-plugin-systemsettings
Configure: none
Builder: qmake
Files:
    - "%{_bindir}/%{name}"
    - "%{_datadir}/applications/%{name}.desktop"
